# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

# We put the entire role in a block so we can create
# a role specific tag, which saves the caller from
# having to do so in their playbook.
- name: Role foolean/apt
  block:

    - name: Set a fact of mountpoints
      ansible.builtin.set_fact:
        mountpoints: "{{ ansible_mounts | map(attribute='mount') | list }}"

    - name: Set remount hook for /var
      become: true
      ansible.builtin.template:
        src: 'etc/apt/apt.conf.d/51remount-var.j2'
        dest: '/etc/apt/apt.conf.d/51remount-var'
        owner: 'root'
        group: 'root'
        mode: '0644'
      when:
        - "'/var' in ansible_mounts"

    - name: Set log permissions hook
      become: true
      ansible.builtin.template:
        src: 'etc/apt/apt.conf.d/99logperms.j2'
        dest: '/etc/apt/apt.conf.d/99logperms'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: Update APT package cache
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: "{{ apt_cache_valid_time }}"


  # This block is only applicable to Debian based systems
  when:
    - ansible_os_family|lower == "debian"

  # Tags to be applied to this role (block)
  tags:
    - 'always'
    - 'role_foolean_apt'
